Repository WildCodeSchool/2409-wns-rouge-ask-and-trust, pull requests merged in 2025-08, with the labels that each got.

#223 chore: update dependencies and refactor frontend components
  app/frontend/Dockerfile
  app/frontend/package.json
  app/frontend/src/components/hoc/PublicRoute.tsx
  app/frontend/src/components/hoc/withSEO.tsx
  app/frontend/src/components/sections/auth/Signup.tsx
  app/frontend/src/components/sections/auth/form/FormButtonSubmit.tsx
  app/frontend/src/components/sections/auth/form/InputEmail.tsx
  app/frontend/src/components/sections/auth/form/InputPassword.tsx
  app/frontend/src/config/client.tsx
  app/frontend/src/main.tsx
  app/frontend/src/styles/theme.css
  package-lock.json
  package.json
Labels: bug

#234 189 feat create the admin page
  app/frontend/src/components/hoc/AdminRoute.tsx
  app/frontend/src/components/sections/auth/AdminRequired.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableSearch.tsx
  app/frontend/src/components/sections/dashboard/UserTable.tsx
  app/frontend/src/components/sections/dashboard/UserTableContainer.tsx
  app/frontend/src/components/sections/dashboard/UserTableHead.tsx
  app/frontend/src/components/sections/dashboard/UserTableNav.tsx
  app/frontend/src/components/sections/dashboard/UserTableRow.tsx
  app/frontend/src/components/ui/TabSwitch.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/data/seo-metadata.ts
  app/frontend/src/graphql/auth.ts
  app/frontend/src/hooks/useUsers.ts
  app/frontend/src/pages/Admin.tsx
  app/frontend/src/types/types.ts
Labels: good first issue

#261 fix: update datasource configuration to run migrations only in produc…
  app/backend/src/database/config/datasource.ts
Labels: bug

#260 fix: in survey creator, check if user owns the survey
  app/frontend/src/pages/SurveyCreator.tsx
Labels: bug

#253 fix: remove useless condition
  app/frontend/src/pages/Surveys.tsx
Labels: bug

#264 feat: in survey creator, header, manage action buttons depending on s…
  app/frontend/src/pages/SurveyCreator.tsx
Labels: bug, enhancement
