Repository WildCodeSchool/2409-wns-rouge-ask-and-trust, pull requests merged in 2025-04, with the labels that each got.

#43 18 feature create card component
  app/frontend/src/components/sections/SurveyCard.tsx
  app/frontend/src/types/types.ts
Labels: good first issue

#44 Fix bg footer, and create page termes of use for the website and upda…
  app/frontend/src/App.tsx
  app/frontend/src/components/sections/footer/Footer.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/pages/TermsOfUse.tsx
Labels: good first issue

#46 45 feature add ci in project
  .github/pull_resquest_template.md
  .github/workflows/check-pull-request-source-branch-workflow.yaml
  .github/workflows/client-tests-workflow.yaml
  .github/workflows/docker-build-workflow.yaml
  .github/workflows/documentation-generation-workflow.yaml
  .github/workflows/linting-and-audit-workflow.yaml
  README.md
  app/frontend/eslint.config.js
  app/frontend/src/__tests__/components-test/footer.spec.tsx
  app/frontend/src/components/hoc/ProtectedRoute.tsx
  app/frontend/src/components/sections/footer/Footer.tsx
  app/frontend/src/components/sections/footer/FooterMobile.tsx
  app/frontend/src/components/sections/header/Header.tsx
  app/frontend/src/components/sections/header/HeaderMobileMenu.tsx
  app/frontend/src/components/sections/header/NavAndButtons.tsx
  app/frontend/src/components/ui/Button.tsx
  app/frontend/src/components/ui/ErrorElement.tsx
  app/frontend/src/components/ui/Loader.tsx
  app/frontend/src/components/ui/separator.tsx
  app/frontend/src/config/client.tsx
  app/frontend/src/contexts/AuthContextProvider.tsx
  app/frontend/src/main.tsx
  app/frontend/src/pages/Home.tsx
  app/frontend/src/pages/TermsOfUse.tsx
  package-lock.json
  package.json
  tsconfig.docs.json
  typedoc.json
Labels: good first issue

#55 Fix docker workflow and add folders in prettierignore
  .github/workflows/check-pull-request-source-branch-workflow.yaml
  .github/workflows/docker-build-workflow.yaml
  .github/workflows/documentation-generation-workflow.yaml
  .prettierignore
Labels: bug

#56 7 feature landing page
  app/frontend/public/assets/check.svg
  app/frontend/public/assets/illustration-presentation.svg
  app/frontend/public/assets/window-group-icons.svg
  app/frontend/src/App.tsx
  app/frontend/src/components/sections/footer/Footer.tsx
  app/frontend/src/components/sections/header/NavAndButtons.tsx
  app/frontend/src/components/sections/landing/Hero.tsx
  app/frontend/src/components/sections/landing/Information.tsx
  app/frontend/src/components/sections/landing/Package.tsx
  app/frontend/src/components/sections/landing/Poll.tsx
  app/frontend/src/components/sections/landing/parts/AllPackages.tsx
  app/frontend/src/components/ui/CompanyBox.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/pages/Home.tsx
  app/frontend/src/pages/Landing.tsx
  app/frontend/src/styles/index.css
Labels: good first issue

#58 fix error in if
  .github/workflows/check-pull-request-source-branch-workflow.yaml
Labels: bug

#57 Develop
  .github/pull_resquest_template.md
  .github/workflows/check-pull-request-source-branch-workflow.yaml
  .github/workflows/client-tests-workflow.yaml
  .github/workflows/docker-build-workflow.yaml
  .github/workflows/documentation-generation-workflow.yaml
  .github/workflows/linting-and-audit-workflow.yaml
  .prettierignore
  README.md
  app/frontend/eslint.config.js
  app/frontend/public/assets/check.svg
  app/frontend/public/assets/illustration-presentation.svg
  app/frontend/public/assets/window-group-icons.svg
  app/frontend/public/img/dev.webp
  app/frontend/src/App.tsx
  app/frontend/src/__tests__/components-test/footer.spec.tsx
  app/frontend/src/components/hoc/ProtectedRoute.tsx
  app/frontend/src/components/sections/footer/Footer.tsx
  app/frontend/src/components/sections/footer/FooterMobile.tsx
  app/frontend/src/components/sections/header/Header.tsx
  app/frontend/src/components/sections/header/HeaderMobileMenu.tsx
  app/frontend/src/components/sections/header/NavAndButtons.tsx
  app/frontend/src/components/sections/landing/Hero.tsx
  app/frontend/src/components/sections/landing/Information.tsx
  app/frontend/src/components/sections/landing/Package.tsx
  app/frontend/src/components/sections/landing/Poll.tsx
  app/frontend/src/components/sections/landing/parts/AllPackages.tsx
  app/frontend/src/components/sections/surveys/Header.tsx
  app/frontend/src/components/sections/surveys/SearchForm.tsx
  app/frontend/src/components/sections/surveys/SurveyCard.tsx
  app/frontend/src/components/ui/Button.tsx
  app/frontend/src/components/ui/CompanyBox.tsx
  app/frontend/src/components/ui/ErrorElement.tsx
  app/frontend/src/components/ui/Loader.tsx
  app/frontend/src/components/ui/Pagination.tsx
  app/frontend/src/components/ui/PaginationContainer.tsx
  app/frontend/src/components/ui/separator.tsx
  app/frontend/src/config/client.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/contexts/AuthContextProvider.tsx
  app/frontend/src/main.tsx
  app/frontend/src/pages/Home.tsx
  app/frontend/src/pages/Landing.tsx
  app/frontend/src/pages/Surveys.tsx
  app/frontend/src/pages/TermsOfUse.tsx
  app/frontend/src/styles/index.css
  app/frontend/src/types/types.ts
  package-lock.json
  package.json
  tsconfig.docs.json
  typedoc.json
Labels: enhancement

#53 31 feature backend - login - register
  app/backend/src/database/entities/user.ts
  app/backend/src/graphql/inputs/create/create-auth-input.ts
  app/backend/src/graphql/inputs/update/update-auth-input.ts
  app/backend/src/graphql/resolvers/auth-resolver.ts
  app/backend/src/services/auth-service.ts
  app/backend/src/types/types.ts
Labels: good first issue

#72 70 feature back for stripe payment
  app/backend/package.json
  app/backend/src/database/entities/payment.ts
  app/backend/src/graphql/inputs/create/create-payment-input.ts
  app/backend/src/graphql/inputs/update/update-payment-input.ts
  app/backend/src/graphql/resolvers/payment-resolver.ts
  app/backend/src/server.ts
  app/backend/src/services/stripe-service.ts
  package-lock.json
  package.json
Labels: bug, good first issue, question

#62 59 feature connexion frontend to registerlogin backend
  app/backend/.env.sample
  app/backend/src/graphql/inputs/create/create-auth-input.ts
  app/backend/src/graphql/resolvers/auth-resolver.ts
  app/backend/src/scripts/create-admin.ts
  app/backend/src/server.ts
  app/backend/src/services/auth-service.ts
  app/frontend/src/components/sections/auth/Signin.tsx
  app/frontend/src/components/sections/auth/Signup.tsx
  app/frontend/src/config/config.ts
  app/frontend/src/graphql/auth.ts
  app/frontend/src/types/types.ts
Labels: good first issue
