Repository WildCodeSchool/2409-wns-rouge-ask-and-trust, pull requests merged in 2025-03, with the labels that each got.

#10 Config repo
  .dockerignore
  app/backend/Dockerfile
  app/backend/package.json
  app/backend/src/graphql/inputs/create/create-auth-input.ts
  app/backend/src/graphql/inputs/update/update-auth-input.ts
  app/backend/src/graphql/resolvers/auth-resolver.ts
  app/backend/src/middlewares/auth-checker.ts
  app/backend/src/middlewares/error-handler.ts
  app/backend/src/resolvers/HelloResolver.ts
  app/backend/src/server.ts
  app/backend/src/services/auth-service.ts
  app/backend/src/types/types.ts
  app/frontend/Dockerfile
  app/frontend/package.json
  app/frontend/src/App.css
  app/frontend/src/App.tsx
  app/frontend/src/components/hoc/ProtectedRoute.tsx
  app/frontend/src/components/sections/Footer.tsx
  app/frontend/src/components/sections/Navigation.tsx
  app/frontend/src/components/ui/ErrorElement.tsx
  app/frontend/src/components/ui/Loader.tsx
  app/frontend/src/config/client.tsx
  app/frontend/src/config/config.ts
  app/frontend/src/config/router.tsx
  app/frontend/src/contexts/AuthContextProvider.tsx
  app/frontend/src/graphql/auth.ts
  app/frontend/src/hooks/useAuth.ts
  app/frontend/src/main.tsx
  app/frontend/src/pages/Auth.tsx
  app/frontend/src/pages/Home.tsx
  app/frontend/src/pages/NotFound.tsx
  app/frontend/src/styles/global.css
  app/frontend/src/types/types.ts
  app/frontend/vite.config.ts
  compose.yaml
  package.json
Labels: enhancement

#15 13 frontend create variables
  .prettierrc
  app/frontend/Dockerfile
  app/frontend/components.json
  app/frontend/package.json
  app/frontend/postcss.config.mjs
  app/frontend/public/fonts/Roboto-VariableFont_wdth,wght.ttf
  app/frontend/src/components/sections/Footer.tsx
  app/frontend/src/index.css
  app/frontend/src/main.tsx
  app/frontend/src/styles/global.css
  app/frontend/src/styles/index.css
  app/frontend/src/styles/theme.css
  app/frontend/tailwind.config.js
  package.json
Labels: good first issue

#22 feat: component Button in ui
  app/frontend/package.json
  app/frontend/src/components/ui/Button.tsx
Labels: good first issue

#23 fix: font format
  app/frontend/src/styles/theme.css
Labels: bug

#25 Harmonise the mobile footer
  app/frontend/src/components/sections/FooterMobile.tsx
  app/frontend/src/types/types.ts
Labels: good first issue

#19 5 feature footer
  app/frontend/package.json
  app/frontend/public/logos/logo-footer.svg
  app/frontend/src/components/sections/Footer.tsx
  app/frontend/src/components/ui/separator.tsx
Labels: good first issue

#27 21 feature unit tests
  .gitignore
  app/frontend/package.json
  app/frontend/src/__tests__/components-test/footer.spec.tsx
  app/frontend/src/__tests__/setupTest.ts
  app/frontend/src/components/sections/Footer.tsx
  app/frontend/vite.config.ts
  package-lock.json
  package.json
Labels: enhancement, good first issue

#28 Create the NotFound Page
  app/frontend/index.html
  app/frontend/package.json
  app/frontend/public/img/errors/undraw_access-denied_krem.svg
  app/frontend/public/img/errors/undraw_attached-file_j0t2.svg
  app/frontend/public/img/errors/undraw_cancel_7zdh.svg
  app/frontend/public/img/errors/undraw_fixing-bugs_13mt.svg
  app/frontend/public/img/errors/undraw_page-not-found_6wni.svg
  app/frontend/public/img/errors/undraw_server-down_lxs9.svg
  app/frontend/public/img/errors/undraw_warning_qn4r.svg
  app/frontend/src/pages/NotFound.tsx
  package-lock.json
Labels: good first issue

#29 6 feature navbar
  app/frontend/package.json
  app/frontend/public/logos/logo-header.svg
  app/frontend/src/App.tsx
  app/frontend/src/__tests__/components-test/footer.spec.tsx
  app/frontend/src/components/sections/Navigation.tsx
  app/frontend/src/components/sections/footer/Footer.tsx
  app/frontend/src/components/sections/footer/FooterMobile.tsx
  app/frontend/src/components/sections/header/Header.tsx
  app/frontend/src/components/sections/header/HeaderMobileMenu.tsx
  app/frontend/src/components/sections/header/NavAndButtons.tsx
  app/frontend/src/components/ui/Button.tsx
  app/frontend/src/styles/index.css
  app/frontend/src/types/types.ts
  package-lock.json
Labels: good first issue
