Repository WildCodeSchool/2409-wns-rouge-ask-and-trust, pull requests merged in 2025-09, with the labels that each got.

#273 Fix hot reaload in safari
  app/backend/.env.sample
  app/frontend/vite.config.ts
  compose.prod.yaml
  compose.staging.yaml
  nginx/nginx.conf
Labels: bug

#277 fix(query): use the correct query if admin or simple user
  app/backend/src/graphql/inputs/queries/surveys-query-input.ts
  app/backend/src/graphql/resolvers/survey/survey-resolver.ts
  app/frontend/src/components/sections/dashboard/SurveyTableContainer.tsx
  app/frontend/src/hooks/useDebounce.ts
  app/frontend/src/hooks/useSurvey.ts
  app/frontend/src/pages/Admin.tsx
  app/frontend/src/pages/Surveys.tsx
  app/frontend/src/pages/UserProfile.tsx
  app/frontend/src/types/types.ts
Labels: good first issue, invalid

#279 251 UI improvement
  app/frontend/src/components/sections/auth/AuthButtons.tsx
  app/frontend/src/components/sections/profile/UserInformations.tsx
  app/frontend/src/components/sections/profile/form/InputResetPassword.tsx
  app/frontend/src/components/sections/profile/parts/ResetPasswordPart.tsx
  app/frontend/src/components/sections/profile/parts/UserDetailsPart.tsx
  app/frontend/src/components/ui/TabSwitch.tsx
  app/frontend/src/pages/Admin.tsx
  app/frontend/src/pages/UserProfile.tsx
Labels: enhancement, good first issue

#288 Docs/deploiement
  docs/deploiement.md
Labels: documentation

#289 refactor: refacto preview survey component and fix HOC"
  app/frontend/src/components/hoc/SurveyRoute.tsx
  app/frontend/src/components/sections/surveys/preview/ContentPreview.tsx
  app/frontend/src/components/sections/surveys/preview/HeaderPreview.tsx
  app/frontend/src/components/sections/surveys/response/ContentResponse.tsx
  app/frontend/src/components/sections/surveys/response/HeaderResponse.tsx
  app/frontend/src/pages/PreviewSurvey.tsx
  app/frontend/src/pages/SurveyResponse.tsx
  app/frontend/src/types/types.ts
Labels: good first issue

#295 fix: fix type question and create missing components
  app/frontend/src/components/sections/preview/QuestionPreview.tsx
  app/frontend/src/components/sections/preview/ui/ReadOnlyRadio.tsx
  app/frontend/src/components/sections/preview/ui/ReadOnlySelect.tsx
  app/frontend/src/components/sections/preview/ui/ReadOnlyTextarea.tsx
  app/frontend/src/components/sections/response/InteractiveQuestion.tsx
  app/frontend/src/components/sections/response/SurveyResponseForm.tsx
  app/frontend/src/components/sections/response/ui/CheckboxInput.tsx
  app/frontend/src/components/sections/response/ui/RadioInput.tsx
  app/frontend/src/components/sections/response/ui/TextareaInput.tsx
Labels: bug

#296 Feature/rate limiting
  app/backend/src/__tests__/rate-limiter.test.ts
  app/backend/src/__tests__/setup.test.ts
  app/backend/src/graphql/resolvers/auth-resolver.ts
  app/backend/src/graphql/resolvers/payment-resolver.ts
  app/backend/src/graphql/resolvers/survey/survey-resolver.ts
  app/backend/src/middlewares/apollo-rate-limiter.ts
  app/backend/src/server.ts
  docs/security-guide.md
Labels: enhancement

#298 286 fix leak user email
  app/backend/src/database/entities/user.ts
  app/backend/src/middlewares/hide-email.ts
Labels: bug

#300 fix: infinite re-render in app.tsx, create RenderHeader and RenderFoo…
  app/backend/src/graphql/resolvers/survey/survey-resolver.ts
  app/frontend/src/App.tsx
  app/frontend/src/components/sections/auth/Signup.tsx
  app/frontend/src/pages/SurveyCreator.tsx
Labels: bug

#303 fix: create survey buttons
  app/frontend/src/components/sections/auth/AuthButtons.tsx
  app/frontend/src/pages/Surveys.tsx
Labels: bug

#311 fix: fix animation links on hover and don't hide them
  app/frontend/src/components/sections/auth/NavAndAuthButtons.tsx
Labels: bug

#313 fix: hide create survey button if not connected and remove dead code
  app/frontend/src/components/sections/dashboard/SurveyTableNav.tsx
  app/frontend/src/components/sections/footer/FooterMobile.tsx
  app/frontend/src/components/ui/Button.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/data/seo-metadata.ts
  app/frontend/src/hooks/survey/useSurveysMutations.ts
  app/frontend/src/pages/SurveyCreate.tsx
  app/frontend/src/pages/SurveyUpdate.tsx
  app/frontend/src/pages/Surveys.tsx
Labels: bug

#317 fix: the pagination displayed all surveys, not just published ones
  app/frontend/src/hooks/useSurvey.ts
  app/frontend/src/pages/Surveys.tsx
Labels: bug
