Repository WildCodeSchool/2409-wns-rouge-ask-and-trust, pull requests merged in 2025-07, with the labels that each got.

#140 refactor: integrate React Hook Form for payment and search forms, enh…
  app/frontend/src/components/payment/StripePaymentForm.tsx
  app/frontend/src/components/sections/contact/ContactForm.tsx
  app/frontend/src/components/sections/preview/SurveySelector.tsx
  app/frontend/src/components/sections/surveys/SearchForm.tsx
Labels: bug, good first issue

#141 136 feature surveys dashboard
  app/backend/src/graphql/resolvers/survey/survey-resolver.ts
  app/frontend/src/components/sections/auth/form/FormWrapper.tsx
  app/frontend/src/components/sections/dashboard/SelectFilter.tsx
  app/frontend/src/components/sections/dashboard/SurveyTable.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableActions.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableContainer.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableFilter.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableNav.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableSearch.tsx
  app/frontend/src/components/ui/Chipset.tsx
  app/frontend/src/components/ui/Pagination.tsx
  app/frontend/src/components/ui/Select.tsx
  app/frontend/src/graphql/survey/survey.ts
  app/frontend/src/pages/Surveys.tsx
  app/frontend/src/types/types.ts
Labels: enhancement, good first issue

#144 Config husky
  .husky/README.md
  .husky/TESTING.md
  .husky/commit-msg
  .husky/husky.sh
  .husky/post-merge
  .husky/pre-commit
  .husky/pre-push
  .lintstagedrc.json
  CHANGELOG.md
  README.md
  app/backend/eslint.config.js
  app/backend/jest.config.js
  app/backend/package.json
  app/backend/src/__tests__/setup.test.ts
  app/backend/tsconfig.json
  app/frontend/README.md
  commitlint.config.js
  package-lock.json
  package.json
  scripts/setup-husky.sh
  scripts/test-husky.sh
Labels: enhancement

#153 151 fix buildquestion answers
  app/backend/src/graphql/resolvers/survey/questions-resolver.ts
  app/backend/src/graphql/utils/authorizations.ts
  app/frontend/src/components/sections/surveys/buildSurvey/question/BuildListAnswers.tsx
  app/frontend/src/components/sections/surveys/buildSurvey/question/BuildQuestion.tsx
Labels: bug

#170 fix: ensure user-specific answer retrieval by adding userId filter in…
  app/backend/src/graphql/resolvers/survey/answers-resolver.ts
Labels: bug, good first issue

#169 34 feature create page profile
  app/frontend/public/img/landing/check.svg
  app/frontend/public/img/landing/illustration-presentation.svg
  app/frontend/public/img/landing/window-group-icons.svg
  app/frontend/public/img/profile/profile-picture.png
  app/frontend/src/App.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableContainer.tsx
  app/frontend/src/components/sections/dashboard/SurveyTableNav.tsx
  app/frontend/src/components/sections/landing/Hero.tsx
  app/frontend/src/components/sections/landing/Information.tsx
  app/frontend/src/components/sections/landing/parts/AllPackages.tsx
  app/frontend/src/components/sections/profile/UserInformations.tsx
  app/frontend/src/components/sections/profile/form/InputResetPassword.tsx
  app/frontend/src/components/sections/profile/parts/ResetPasswordPart.tsx
  app/frontend/src/components/sections/profile/parts/UserDetailsPart.tsx
  app/frontend/src/components/sections/surveys/Header.tsx
  app/frontend/src/components/ui/Chipset.tsx
  app/frontend/src/components/ui/Select.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/pages/Landing.tsx
  app/frontend/src/pages/UserProfile.tsx
  app/frontend/src/styles/index.css
  app/frontend/src/types/types.ts
  package-lock.json
Labels: good first issue

#192 182 style clean style surveycreator
  app/frontend/src/components/sections/Toolbox/AdaptativeToolbox.tsx
  app/frontend/src/components/sections/Toolbox/Toolbox.tsx
  app/frontend/src/components/sections/canvas/Canvas.tsx
  app/frontend/src/components/sections/surveys/Header.tsx
  app/frontend/src/components/sections/surveys/buildSurvey/question/BuildQuestion.tsx
  app/frontend/src/components/ui/ButtonScroll.tsx
  app/frontend/src/components/ui/Input.tsx
  app/frontend/src/pages/SurveyCreator.tsx
  app/frontend/src/styles/theme.css
  app/frontend/src/styles/toolbox.css
Labels: bug, enhancement

#195 184 fix add paragraph question
  app/frontend/src/components/sections/Toolbox/AdaptativeToolbox.tsx
  app/frontend/src/components/sections/Toolbox/toolboxData.tsx
Labels: bug

#205 feat: add Disaster Recovery Plan documentation for Ask&Trust
  SERVER.MD
  docs/disaster-recovery-plant.md
Labels: good first issue

#207 196 feat canvas table content questions
  app/frontend/src/components/sections/Toolbox/AdaptativeToolbox.tsx
  app/frontend/src/components/sections/canvas/Canvas.tsx
  app/frontend/src/components/sections/canvas/TableContentQuestions.tsx
  app/frontend/src/components/sections/surveys/buildSurvey/question/BuildQuestion.tsx
Labels: enhancement
