Repository WildCodeSchool/2409-wns-rouge-ask-and-trust, pull requests merged in 2025-05, with the labels that each got.

#82 Fix bug proxy
  app/backend/.env.sample
  app/backend/src/server.ts
  app/frontend/src/config/client.tsx
  app/frontend/src/config/config.ts
  nginx/nginx.conf
  package-lock.json
Labels: bug, enhancement

#90 63 feature add toaster
  app/frontend/package.json
  app/frontend/src/App.tsx
  app/frontend/src/components/sections/auth/Signin.tsx
  app/frontend/src/components/sections/auth/Signup.tsx
  app/frontend/src/components/sections/auth/form/InputFirstname.tsx
  app/frontend/src/components/sections/auth/form/InputLastname.tsx
  app/frontend/src/hooks/useToast.ts
  app/frontend/src/main.tsx
  app/frontend/src/styles/theme.css
  package-lock.json
Labels: enhancement

#104 feat(toolbox): improve toolbox UI, code structure, and documentation
  app/frontend/package.json
  app/frontend/src/components/Toolbox/AdaptativeToolbox.tsx
  app/frontend/src/components/Toolbox/Toolbox.tsx
  app/frontend/src/components/Toolbox/toolboxData.tsx
  app/frontend/src/config/router.tsx
  app/frontend/src/hooks/useResponsivity.ts
  app/frontend/src/pages/SurveyCreator.tsx
  app/frontend/src/styles/toolbox.css
  app/frontend/src/types/types.ts
  package-lock.json
Labels: good first issue
